### ISSUE TITLE
fails to build with ghc-9.6 stackage nightly

### ISSUE THREAD

**Issue by juhp** [alephcloud/hs-configuration-tools#83]
```
       Building library for configuration-tools-0.6.1..                                                                             
       [11 of 13] Compiling Configuration.Utils                                                                                     
                                                                                                                                    
       /var/stackage/work/unpack-dir/unpacked/configuration-tools-0.6.1-a4d8ab36e66d452ec3007201723df0ea827f1bf7cfd3cd94cd3e6d09c1c3
d8e6/src/Configuration/Utils.hs:742:5: error: [GHC-88464]                                                                           
           Variable not in scope: void :: m0 ((), f T.Text) -> m a0                                                                 
           |                                                                                                                        
       742 |     void ∘ validate appInfo $ _mainConfig appConf                                                                      
           |     ^^^^                                                                                                               
                                                                                                                                    
       /var/stackage/work/unpack-dir/unpacked/configuration-tools-0.6.1-a4d8ab36e66d452ec3007201723df0ea827f1bf7cfd3cd94cd3e6d09c1c3
d8e6/src/Configuration/Utils.hs:765:5: error: [GHC-88464]                                                                           
           Variable not in scope: when :: Bool -> IO () -> IO ()                                                                    
           |                                                                                                                        
       765 |     when (any (const True) warnings) $ do                                                                              
           |     ^^^^
```

**Comment by larskuhtz** [comment]
This should be solved in version 0.7.0
